valid_player_tags = ["#2RRLQR2R9",
                     "#PJU928JR",
                     "#9GJ290PU2",
                     "#YLGYP9J8",
                     "#8922J0Y0P",
                     "#8Q09QYLQ",
                     "#8R2VV0VU",
                     "#8QR0LYYP",
                     "#8GP029V2L",
                     "#LRJPULVP",
                     "#2GVRGYLPP",
                     "#2Q0GGGRQ8",
                     "#8LQUVVU9",
                     "#PUPU9RVJ",
                     "#2YVRU9UYY",
                     "#LG09Q8PC",
                     "#PP8992LU",
                     "#2CVCYRQUV",
                     "#GJ0YCRR9",
                     "#L2Y0L8CV",
                     "#J82UQLPJ",
                     "#2VQ0U8CPQ",
                     "#G8G2RRPC",
                     "#2P02P0LQ9",
                     "#2LCGQG09L",
                     "#RVP02LU0",
                     "#P8GJYQ0PU",
                     "#8CYCC08R0",
                     "#89QL9CL2",
                     "#98J2VLYU",
                     "#9JUQCYL",
                     "#8RQP2GJ2",
                     "#QQ8PQJ2C",
                     "#YQLQ2PYY",
                     "#GRPJJQ2U",
                     "#2G92L9G08",
                     "#28U0JJJU2",
                     "#28G2YQY2G",
                     "#L8GV928LQ",
                     "#2VJLQ8UU",
                     "#L9LL8QJY8",
                     "#RYPRUURU",
                     "#LJ92VQLU",
                     "#L0YUCJPQ8",
                     "#P8YU2R9R2",
                     "#PJ20CVUJR",
                     "#9RVQY9JPG",
                     "#L0GJYCLGJ",
                     "#L0Y09LJVL",
                     "#YCLV8JRJ9",
                     ]

garbled_player_tags = ["  #2RRLQR2R9  ",
                       "PJU928JR",
                       "  #9GJ29OPU2",
                       "#YLGYP9J8  ",
                       "#8922JOYOP",
                       "#8qO9qylq",
                       "#8R2VVOVU",
                       "#8qROLYYP",
                       "#8GPO29V2L",
                       "#lrjpulvp  ",
                       "#2GVRGYLpp",
                       "#2QOGGGRQ8",
                       "8LQUVVU9",
                       "PUPU9RVJ",
                       "2YVRU9UYY",
                       "LGO9Q8PC",
                       "PP8992LU  ",
                       "2cvcYRQUV",
                       "#GJOYCRR9",
                       "#L2YOL8CV",
                       " j82uqlpj",
                       "  2VQOU8CPQ  ",
                       "G8G2RRPC  ",
                       "#2PO2POLQ9",
                       "#2LCGQGO9L",
                       "#RvPo2LuO",
                       "#P8GJYQOPU",
                       " 8CYCCO8RO ",
                       "#89QL9CL2  ",
                       "#98j2vlyu ",
                       "#9JUQCYL  ",
                       "#8Rqp2Gj2       ",
                       "#QQ8P     QJ2C",
                       "# Y Q L Q 2 P Y Y",
                       "#GRPJJQ2u  ",
                       "#2G92L9GO8",
                       "# 28UOJJJU2",
                       "28G2YQY2G",
                       "#l8GV928LQ",
                       "# 2VJLQ8UU",
                       " #l9Ll8QJY8",
                       "#RYPRUURU    ",
                       "%#LJ92VQLU",
                       "-#LOYUCJPQ8",
                       "!#P8YU2R9R2",
                       "@PJ2OCVUJR",
                       "!9RVQY9JPG",
                       "/LOGJYCLGJ",
                       ":LOYO9LJVL",
                       "YCLV8JRJ9",
                       ]

valid_clan_tags = ["#2VR2YY0G",
                   "#J8P0PYRL",
                   "#LVJVJ2QL",
                   "#P8V0CVLQ",
                   "#P9YP2UVL",
                   "#Q2GURP2G",
                   "#PCR8YJ2J",
                   "#YRPJ280Y",
                   "#29LG0JLJ",
                   "#2VL20Y9",
                   "#80CY9R0V",
                   "#U9CGQJC",
                   "#2RV2UPYY",
                   "#P2RLC29",
                   "#2YU22YY",
                   "#LQLC0PGJ",
                   "#9L2VP828",
                   "#LJLCLUPC",
                   "#PPRYPY80",
                   "#L9VP28R0",
                   "#LL0UP8JP",
                   "#PG0R9Q0L",
                   "#LV2LL0L8",
                   "#9GP02C22",
                   "#JC2PY89",
                   "#RUQ9GUGL",
                   "#2U2CYPQ8",
                   "#GL8CGV0",
                   "#P9QV02UY",
                   "#LQY2JUCJ",
                   "#Q98980G2",
                   "#GQYPV2RG",
                   "#RC0C2PJ0",
                   "#YPCPVGL9",
                   "#Q9QRYRV9",
                   "#892CJQLP",
                   "#JYPRJVU",
                   "#2L20QYR9",
                   "#2UCR8R9P",
                   "#8YQU929P",
                   "#PJY0J8GP",
                   "#2CCV0U9V",
                   "#PY9VL90C",
                   "#8L2QP98J",
                   "#2LG0000",
                   "#VJQVU0J",
                   "#CUL0PYV",
                   "#80UUQCRU",
                   "#PYRV8RVL",
                   "#J882PQCY",
                   "#2P0YQU8P",
                   "#J09QGQ2",
                   "#PVUGQJ2U",
                   "#JLY899U",
                   "#J9CRVV82",
                   "#GR092LQ0",
                   "#8RPV999Y",
                   "#2JGYRJVL",
                   "#LVYQQLUY",
                   "#UPC9GUJ",
                   "#98U2CGGL",
                   "#9QVRJ9Q",
                   "#Q9VUQ",
                   "#9L02Y929",
                   "#UPYJ",
                   "#PC0CLGLQ",
                   "#PUC9YGRP",
                   "#P8YCGCQ9",
                   "#GJ0Q0L2",
                   "#2LY88G2C",
                   "#RPYQQJJ",
                   "#822RCUPV",
                   "#9YQRPL2C",
                   "#J9PRJ2G9",
                   "#20L9UVVP",
                   "#PQQVVR2L",
                   "#800VYPCG",
                   "#8VYLCJJ2",
                   "#8UY829U8",
                   "#8UPJGYL9",
                   "#9QV9P0JR",
                   "#2RYQYQRY",
                   "#L2LUL0R0",
                   "#2RLQRP8L",
                   "#C99CQC8L",
                   "#YRLJ8CJY",
                   "#2RYL0GCP",
                   "#28GLLVUU",
                   "#PUL0VVGU",
                   "#9LJJU00Y",
                   "#2UJ9CGJ8",
                   "#CLCPC89",
                   "#U0V92LQY",
                   "#PPJYC8Q",
                   "#RRJGV22Y",
                   "#LC20PGQJ",
                   "#22R80YJP",
                   "#2PL8UQRP0",
                   "#8GRVGRV8",
                   "#Q8UVC22Y",
                   "#9R02JYYC",
                   "#JLPGYQV",
                   "#8QQYCLR0",
                   "#G889JQ9R",
                   "#9VQ2YULV",
                   "#QVJLUL20",
                   "#P99928LJ",
                   "#90G2R8JR",
                   "#22Q22GJQ",
                   "#PG9V0UJ",
                   "#20JLLG20",
                   "#JYCCPJ90",
                   "#V0LV8J0",
                   "#GP99C0J",
                   "#YJL0RUYL",
                   "#2YCL88Q8",
                   "#20JGG8UQ2",
                   "#2LURGU09",
                   "#8VP0JQV9",
                   "#9LRGLLQ",
                   "#2RUU0VP9",
                   "#90PU08VU",
                   "#9YPRG0J8",
                   "#8RQ9C9Q2",
                   "#9PCRV8CG",
                   "#8R8RQGYJ",
                   "#P2VRCJQG",
                   "#8RGJY0CP",
                   "#L20C9V02",
                   "#8JGC02P0",
                   "#JGU9J2CQ",
                   "#Y9RYU009",
                   "#8J28VG9Y",
                   "#22PLQU9C",
                   "#9JJGPCRU",
                   "#LQ2GVQYV",
                   "#U8GRVG0",
                   "#980CVJYU",
                   "#8QRYVUVQ",
                   "#2JLQRQRC",
                   "#22999UYV8",
                   "#UGUUGJJ",
                   "#9RPVG8UP",
                   "#L2YRQ9RQ",
                   "#29QRR0C2",
                   "#2PCC9YL8",
                   "#20JRUGGY2",
                   "#CYJP9YG",
                   "#Q9PLUU2V",
                   "#28YYPQ89",
                   "#CJR20GC",
                   "#U2Q0GUL",
                   "#L20Q2QGR",
                   "#YRV8UV9C",
                   "#L9P8YLR",
                   "#V99CQ9LY",
                   "#U9R2PPR",
                   "#LLCCLPJ",
                   "#PCUC89RG",
                   "#VV2GUUP",
                   "#PYCY8UYR",
                   "#2QQCLCY0",
                   "#V0P908YG",
                   "#PYL20GL0",
                   "#92RGCLQL",
                   "#LUQLYV20",
                   "#LRLV29VL",
                   "#PCPVRYUY",
                   "#Q0QCVULP",
                   "#9PLV82Y8",
                   "#82P08R9G",
                   "#8UYPRV8V",
                   "#20UJYY2",
                   "#YQPLJJPL",
                   "#2VYCYJ92",
                   "#Y9GVLUV",
                   "#UJQLGRL",
                   "#89Y0RUQY",
                   "#LQL0VUU9",
                   "#PUV9P9YQ",
                   "#VQLQJVC",
                   "#GC0QJ9QY",
                   "#L9G2YCPL",
                   "#PG88PU9U",
                   "#R02LLQJV",
                   "#2LU2QGG2",
                   "#GJG8QVR8",
                   "#9L98VQCJ",
                   "#PQCQ8CRP",
                   "#2QC9GUG",
                   "#VP0Q2J",
                   "#9PVUVLC8",
                   "#LLPUJ8VU",
                   "#9VR0QC8R",
                   "#9L0P2QVY",
                   "#Q028VVYU",
                   "#9VPLY8Q9",
                   "#P802G89U",
                   "#20J8RRLG2",
                   "#98U8QPQL",
                   ]

garbled_clan_tags = ["#2VR2YY0G  ",
                     "J8P0PYRL  ",
                     "#LVJVJ2QL    ",
                     "              P8V0CVLQ",
                     "#P9YP      2UVL",
                     "q 2 GURP 2 G",
                     "#PcR8YJ2J",
                     "YRPJ280Y  ",
                     "#29LG0 J LJ",
                     "2VL2OY9",
                     "   #8OCY9ROV",
                     "U9CGQJC",
                     "#2RV2UPYY",
                     "P2RLC29",
                     "#2YU22YY",
                     "LQLCOPGJ",
                     "#9L2VP828",
                     "LJLCLUPC",
                     "#PPRYPY8O",
                     "L9VP28RO",
                     "#LLOUP8JP",
                     "PGOR9QOL",
                     "#LV2LLOL8",
                     "9GPO2C22",
                     "#JC2PY89",
                     "RUQ9GUGL",
                     "  #2U2CYPQ8",
                     "GL8CGVO",
                     "#P9QVO2UY",
                     "LQY2JUCJ",
                     "#Q9898OG2",
                     "GQYPV2RG",
                     "#RCOC2PJO",
                     "YPCPVGL9",
                     "#Q9QRYRV9",
                     "892CJQLP",
                     "#JYPRJVU",
                     "2L2oQYR9",
                     "#2UCR8R9P",
                     "8YQU929P",
                     "#PJYoJ8GP",
                     "2CCVoU9V",
                     "#PY9VL9oC",
                     "8L2QP98J",
                     "#2LGoooo",
                     "VJQVUoJ",
                     "#CULoPYV",
                     "8oUUQCRU",
                     "#PYRV8RVL",
                     "J882PQCY",
                     "#2PoYQU8P",
                     "Jo9QGQ2",
                     "#PVUGQJ2U",
                     "JLY899U",
                     "#J9CRVV82",
                     "GRo92LQ0",
                     "#8RPV999Y",
                     "2JGYRJVL",
                     "#LVYQQLUY",
                     "UPC9GUJ",
                     "#98U2CGGL",
                     "9QVRJ9Q",
                     "#Q9VUQ",
                     "9L02Y929",
                     "uPyJ",
                     "PC0CLGLQ",
                     "#PUC9YGRP",
                     "P8YCGCQ9",
                     "#GJ0Q0L2",
                     "2LY88G2C",
                     "#RPYQQJJ",
                     "822RCUPV",
                     "#9YQRPL2C",
                     "J9PRJ2G9",
                     "#20L9UVVP",
                     "PQQVVR2L",
                     "#800VYPCG",
                     "8VYLCJJ2",
                     "#8UY829U8",
                     "8UPJGYL9",
                     "#9QV9P0JR",
                     "2RYQYQRY",
                     "#L2LUL0R0",
                     "2RLQRP8L",
                     "#C99CQC8L",
                     "YRLJ8CJY",
                     "#2R YL0GCP",
                     "28GLLVUU",
                     "#PUL0VVGU",
                     "@@@9LJJU00Y",
                     "#2UJ9CGJ8",
                     "CLCPC89",
                     "!U0V92LQY",
                     "-PPJYC8Q",
                     "#RRJGV22Y",
                     "LC20PGQJ",
                     "#22R80YJP",
                     "2PL8UQRP0",
                     "#8GRVGRV8",
                     "Q8UVC22Y",
                     "#9R02JYYC",
                     "JLPGYQV",
                     "#8QQYCLR0",
                     "G889JQ9R",
                     "#9VQ2YULV",
                     "QVJLUL20",
                     "#P99928LJ",
                     "90G2R8JR",
                     "#22Q22GJQ",
                     "PG9V0UJ",
                     "#20JLLG20",
                     "JYCCPJ90",
                     "#V0LV8J0",
                     "@GP99C0J",
                     "#YJL0RUYL",
                     "#2YCL88Q8",
                     "#20JGG8UQ2",
                     "!2LURGU09",
                     "#8VP0JQV9",
                     "#9LRGLLQ",
                     "  #2 RUU0VP 9  ",
                     "# 90PU08VU",
                     "  #9YPRG0J8",
                     "#8RQ9C9Q2  ",
                     "#9PC RV8CG",
                     "#8r8rqgYJ",
                     "p2vrcjqg",
                     "   #8RGJY0CP",
                     "#L2oC9V02",
                     "  #8JGC02P0",
                     " #JGU9J2CQ ",
                     "Y9RYU009",
                     "8J28VG9Y",
                     "22PLQU9C",
                     "9JJGPCRU",
                     "LQ2GVQYV",
                     "U8GRVG0",
                     "980CVJYU",
                     "8QRYVUVQ",
                     "2JLQRQRC",
                     "22999UYV8",
                     "UGUUGJJ",
                     "9RPVG8UP",
                     "L2YRQ9RQ",
                     "29QRR0C2",
                     "2PCC9YL8",
                     "20JRUGGY2",
                     "CYJP9YG",
                     "Q9PLUU2V",
                     "28YYPQ89",
                     "#CJR2OGC ",
                     "#U2QOGUL ",
                     "#L2OQ2QGR ",
                     "#YRV8UV9C ",
                     "#L9P8YLR ",
                     "#V99CQ9LY ",
                     "#U9R2PPR ",
                     "#LLCCLPJ ",
                     "#PCUC89RG ",
                     "#VV2GUUP ",
                     "#PYCY8UYR ",
                     " #2QQCLCYO",
                     " #VOP9O8YG",
                     " #PYL2OGLO",
                     " #92RGCLQL",
                     " #LUQLYV2O",
                     " #LRLV29VL",
                     " #PCPVRYUY",
                     " #QOQCVULP",
                     "9PLV82Y8",
                     "82PO8R9G",
                     "8UYPRV8V",
                     "2OUJYY2",
                     "YQPLJJPL",
                     "2VYCYJ92",
                     "Y9GVLUV",
                     "UJQLGRL",
                     "89YORUQY",
                     "LQLOVUU9",
                     "PUV9P9YQ",
                     "VQLQJVC",
                     "GCOQJ9QY",
                     "#L 9G2YCPL",
                     "#_PG88PU9U",
                     "# RO2LLQJV",
                     "# 2LU2QGG2",
                     "# GJG8QVR8",
                     "          #9L98VQCJ",
                     "#pQCQ8CRP ",
                     "##2QC9GUG",
                     "!#VPOQ2J",
                     "@ 9PVUVLC8",
                     " LLPUJ8VU",
                     "#9VROQC8R",
                     "#9LOP2QVY",
                     "#QO28VVYU",
                     " 9 VPLY8Q9",
                     " P8O2G89U",
                     "#2OJ8RRLG2",
                     "#98U8QPQL ",
                     ]

prefixes = ["!", "?", "@", "-", "$", "%", "*"]
