valid_player_tags = ["#2RRLQR2R9",
                     "#PJU928JR",
                     "#9GJ290PU2",
                     "#YLGYP9J8",
                     "#8922J0Y0P",
                     "#8Q09QYLQ",
                     "#8R2VV0VU",
                     "#8QR0LYYP",
                     "#8GP029V2L",
                     "#LRJPULVP",
                     "#2GVRGYLPP",
                     "#2Q0GGGRQ8",
                     "#8LQUVVU9",
                     "#PUPU9RVJ",
                     "#2YVRU9UYY",
                     "#LG09Q8PC",
                     "#PP8992LU",
                     "#2CVCYRQUV",
                     "#GJ0YCRR9",
                     "#L2Y0L8CV",
                     "#J82UQLPJ",
                     "#2VQ0U8CPQ",
                     "#G8G2RRPC",
                     "#2P02P0LQ9",
                     "#2LCGQG09L",
                     "#RVP02LU0",
                     "#P8GJYQ0PU",
                     "#8CYCC08R0",
                     "#89QL9CL2",
                     "#98J2VLYU",
                     "#9JUQCYL",
                     "#8RQP2GJ2",
                     "#QQ8PQJ2C",
                     "#YQLQ2PYY",
                     "#GRPJJQ2U",
                     "#2G92L9G08",
                     "#28U0JJJU2",
                     "#28G2YQY2G",
                     "#L8GV928LQ",
                     "#2VJLQ8UU",
                     "#L9LL8QJY8",
                     "#RYPRUURU",
                     "#LJ92VQLU",
                     "#L0YUCJPQ8",
                     "#P8YU2R9R2",
                     "#PJ20CVUJR",
                     "#9RVQY9JPG",
                     "#L0GJYCLGJ",
                     "#L0Y09LJVL",
                     "#YCLV8JRJ9",
                     ]

garbled_player_tags = ["  #2RRLQR2R9  ",
                       "PJU928JR",
                       "  #9GJ29OPU2",
                       "#YLGYP9J8  ",
                       "#8922JOYOP",
                       "#8qO9qylq",
                       "#8R2VVOVU",
                       "#8qROLYYP",
                       "#8GPO29V2L",
                       "#lrjpulvp  ",
                       "#2GVRGYLpp",
                       "#2QOGGGRQ8",
                       "8LQUVVU9",
                       "PUPU9RVJ",
                       "2YVRU9UYY",
                       "LGO9Q8PC",
                       "PP8992LU  ",
                       "2cvcYRQUV",
                       "#GJOYCRR9",
                       "#L2YOL8CV",
                       " j82uqlpj",
                       "  2VQOU8CPQ  ",
                       "G8G2RRPC  ",
                       "#2PO2POLQ9",
                       "#2LCGQGO9L",
                       "#RvPo2LuO",
                       "#P8GJYQOPU",
                       " 8CYCCO8RO ",
                       "#89QL9CL2  ",
                       "#98j2vlyu ",
                       "#9JUQCYL  ",
                       "#8Rqp2Gj2       ",
                       "#QQ8P     QJ2C",
                       "# Y Q L Q 2 P Y Y",
                       "#GRPJJQ2u  ",
                       "#2G92L9GO8",
                       "# 28UOJJJU2",
                       "28G2YQY2G",
                       "#l8GV928LQ",
                       "# 2VJLQ8UU",
                       " #l9Ll8QJY8",
                       "#RYPRUURU    ",
                       "%#LJ92VQLU",
                       "-#LOYUCJPQ8",
                       "!#P8YU2R9R2",
                       "@PJ2OCVUJR",
                       "!9RVQY9JPG",
                       "/LOGJYCLGJ",
                       ":LOYO9LJVL",
                       "YCLV8JRJ9",
                       ]

invalid_tags = ["#Fred",
                "#C",
                "#CVCJR899GRX7",
                ]

prefixes = ["!", "?", "@", "-", "$", "%", "*"]
